version: '3'

services:
  api1: &api
    command: node server.js
    image: node:20.11-alpine
    hostname: api1
    container_name: api1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '${DOCKER_API1_PORT}:8080'
    depends_on:
      - database
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_PORT: ${DATABASE_PORT}
  api2:
    <<: *api
    hostname: api2
    container_name: api2
    ports:
      - '${DOCKER_API2_PORT}:8080'
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_PORT: ${DATABASE_PORT}

  nginx:
    image: nginx:1.25.3-alpine
    container_name: loadbalancer
    volumes:
      - .docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '${DOCKER_LB_PORT}:9999'

  database:
    image: couchdb:3.3
    container_name: database
    ports:
      - '${DOCKER_DB_PORT}:5984'
    volumes:
      - .docker/data/database:/data/db
      - .docker/config/couchdb/couchdb.ini:/opt/couchdb/etc/local.d/999-docker.ini
    environment:
      COUCHDB_USER: ${DATABASE_USER}
      COUCHDB_PASSWORD: ${DATABASE_PASS}
      COUCHDB_SECRET: ${DATABASE_SECRET}
      NODENAME: ${DATABASE_NODE}
